Repository kfmp/gitest, pull requests merged in 2024-07, with the labels that each got.

#4 feat: 인증 및 인가 구현 [#3]
  js/auth.js
  js/cheolwon.js
Labels: ✨ Feature

#7 feat: 회원가입 구현 [#6]
  js/sign.js
Labels: ✨ Feature

#8 feat: 로그인 구현 [#5]
  css/login.css
  js/login.js
  js/sanghak.js
Labels: ✨ Feature

#9 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Setting

#13 init: 게시판 프로젝트 생성
  .prettierrc.json
  css/login.css
  css/reset.css
  images/1.png
  index.html
  js/auth.js
  js/login.js
  js/sign.js
  package-lock.json
  package.json
Labels: ⚙ Setting, 🎨 Html&css

#15 게시글 생성 및 조회
  api/post.js
  index.html
  js/app.js
  js/post.js
  utils/store.js
Labels: ✨ Feature

#17 상세 페이지 기능
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc.json
  .vscode/settings.json
  api/post.js
  css/reset.css
  images/1.png
  index.html
  js/app.js
  js/auth.js
  js/post.js
  js/sanghak.js
  package-lock.json
  package.json
  utils/store.js
Labels: ✨ Feature

#20 게시글 수정 구현
  index.html
  js/post.js
Labels: ✨ Feature

#21 게시판 삭제기능
  js/post.js
Labels: ✨ Feature
